### ISSUE TITLE
Suggestion to Mention Shneiderman's Mantra

### ISSUE THREAD

**Issue by pfontana3w2** [cathrynploehn-NIST/Visualizationintroduction#1]
Cathryn,

I noticed that in the file `Guiding Principles of Information Visualization.md` you cited Shneiderman's famous work

>  **The Eyes Have It: A Task by Data Type Taxonomy for Information Visualizations.** Ben Shneiderman

But didn't mention his mantra "Overview first, zoom and filter, then details-on-demand" in the text. Perhaps this is worth a sentence or two?

**Comment by cathrynploehn-NIST** [comment]
Yes, I was definitely working on devoting a section to that :)

**Comment by cathrynploehn-NIST** [comment]
Done
