### ISSUE TITLE
Vague Link

### ISSUE THREAD

**Issue by pfontana3w2** [cathrynploehn-NIST/Visualizationintroduction#2]
In your file `Semiology of visualization.md' You write the link

> Shneiderman also defines [seven tasks to accompany these data types](Assessing Information Visualization.md). 

When I clicked on the link and read the page, I could not find the seven tasks (which I believe are the seven he describes in his paper

> Shneiderman, B. (1996, September). The eyes have it: A task by data type taxonomy for information visualizations. In Visual Languages, 1996. Proceedings., IEEE Symposium on (pp. 336-343). IEEE.

Where is your description of the tasks located in the file?

Best Wishes,
Peter Fontana

**Comment by cathrynploehn-NIST** [comment]
Fixed by specifying the citation!
